function out=read_rand_forcing2(casename,nT,nQ,i)
path='../data/';
nc=[path 'RCE_randmultsine_run_1024_' casename '_' int2str(i) '.nc'];
T=double(ncread(nc,'TABS'));
Q=double(ncread(nc,'QV'));
Y=[T(1:nT,:); Q(1:nQ,:)];
dT=double(ncread(nc,'TTENDR'));
dQ=double(ncread(nc,'QTENDR'));
U=[dT(1:nT,:); dQ(1:nQ,:)];
P=double(ncread(nc,'PREC'));
LHF=double(ncread(nc,'LHF'));
p=double(ncread(nc,'p'));
out.U=U;
out.Y=Y;
out.P=P;
out.LHF=LHF;
out.p=p;